---
name: Nicole
surname: Brewer
position: "Research Software Engineer | Graduate Research Assistant"
address: "Arizona State University, Tempe, AZ"
#phone: +1 22 3333 4444
www: nicole-brewer.com
#email: "brewer36@purdue.edu"
twitter: catch_me_coding
github: nicole-brewer
linkedin: nicole-brewer
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
headcolor: '000000'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
library(rorcid)
library(dplyr)
library(rcrossref)
```

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~ Info,
  "PhD Computational History and Philosophy of Science", "Expected May 2027", "Arizona State University", "Tempe, AZ", c("Using natural language processing, machine learning, network analysis, agent-based modeling, high performance computing (HPC) resources, and ethnographic and social science methods to better understand how scientific standards of practice are motivated by reproducibility and other values"),
  "BS Mathematics with Computer Science", "December 2018", "Purdue Univeristy", "West Lafayette, IN", c("Implemented and ran the KMP string matching algorithm in parallel to create a combinatorial game theory set"),
) %>% 
  detailed_entries(Degree, Year, Institution, Where, Info)
```
# Grants, Fellowhips, and Awards

```{r}
tribble(
  ~Year, ~Desc, ~Title, ~Awarder,
  '2022', '', '\\textbf{School of Life Science Fellowship} (\\$2,500), Arizona State University', '',
  '2021', "Travel support for early career scholars who are considering pursuing philosophy of science", '\\textbf{UPSS Delegate} (\\$500), Philosophy of Science Biennial Meeting', '',
  '2020', "Honorarium awarded for notable achievement in the advancement of science gateways", '\\textbf{Young Professional of the Year} (\\$500), Science Gateways Community Institute', '',
  '2018', 'Travel support to attend PEARC18 and participate in the student program', '\\textbf{Travel Grant} (\\$500), XSEDE', '',
  '2018', 'Awarded for "Classification of Periodicity in Subtraction Game Sequences"', '\\textbf{Phil Andrews Award}, Practice and Experience in Advanced Research Computing Conference', ''
) %>% 
  brief_entries(what=Title, when=Year, with=Awarder, .protect = FALSE)
```

# Publications

```{r}
# load from a file
# knitr::write_bib(c("vitae", "tibble"), "packages.bib")

# load from ORCID
# knit requires ORCID_TOKEN in .Renviron
# rcrossref requires crossref_email in .Renviron
source('orcid2bib.R')
ORCID = '0000-0002-6723-8940'

# create a pubs.bib file that contains specific types of works from orcid user
paper_types <- c('journal-article', 'conference-paper')
orcid2bib(ORCID, 'pubs', paper_types)

# combine text from pubs.bib and manual_entry
combined_bib <- c(readLines("pubs.bib"), "\n", readLines("manual_entry.bib"))
writeLines(combined_bib, "combined.bib")

# sort entries by date issued
bibliography_entries("combined.bib") %>%
  arrange(desc(issued))
```

# Presentations
```{r}
# if no url, use \\newline
tribble( 
 ~ title, ~ type, ~ event, ~ place, ~ date, ~ url,
 "Software Engineering Topics Relevant to eScience", "Invited Panelist", "eScience 2022", "Salt Lake City, UT", "Oct 2022", '\\newline',
   "How to Recruit and Sustain a Diverse and Inclusive Workforce: A Case Study",  "Invited Panelist", "International RSE Day", "Virtual", "Oct 2021", "\\url{https://us-rse.org/events/2021/2021-10-intnl-rse-day}",
 "Leveraging Traits for Highly Interactive Computational Tools in Jupyter", "Abstract, Video Presentation", "Gateways 2021", "Virtual", 'July 2021', "\\url{https://doi.org/10.5281/zenodo.5570605}",
 "Classification of Periodicity in Subtraction Game Sequences", "Poster", "PEARC18", "Pittsburg, PA", 'June 2018', '\\newline' ) %>% 
  brief_entries(glue::glue('\\textbf{<title>} (<type>), <event>, <place>. <url>', .open = "<", .close = ">"), paste0(date, "\\newline"), .protect = FALSE)
```

# Professional Experience
```{r}
tribble(
  ~ Job, ~ Year, ~ Institution, ~ Where, ~Desc,
  "Research Software Engineer", "Feb 2019 - Present", "ITaP Research Computing", "Purdue University", list('Implemented a highly interactive, Jupyter-based, GUI wrapper for power analysis software in order to expand the audience and ease of use of a rich set of computational functions via a user-friendly interface', 
  'Facilitated software design, the implementation of best practices, and internal tool development, and lab documentation to improve the overall sustainability of lab software',
  'Transform disparate data acquisition and processing scripts into modular classes to be reused for scientific workflows'),
  'Software Verification Engineer', 'Nov 2017 – Nov 2018', 'Aptiv', 'West Lafayette, IN',
  'Developed comprehensive Unit Test projects that utilized CAN bus protocol communications to verify automotive controller hardware', 
) %>% 
  detailed_entries(Job, Year, Institution, Where, Desc)
  # 'Designed a dynamic Solr schema to index and query layered geospacial and user-defined metadata', 
  #'Implemented interactions with this database in a web application in PHP and JavaScript',
  #'Mentored students participating in semester-long internships'
```

# Research Experience
```{r}
tribble(
  ~Year, ~Type, ~Institution, ~Desc,
  'Aug 2022 - Present', 'Graduate Research Assistant', 'Center for Biology and Society, Arizona State University', 'Advisor: Manfred Laubichler',
  'June 2018 - Dec 2018', 'Student Cluster Competition Team', 'Research Computing, Purdue University', list('Built a small cluster and applied optimization techniques in a non-stop, 48-hour challenge at the SC18 conference', 'Compiled a scienfitic application from an accepted paper from the prior year’s Technical Program and interacted directly with the paper’s authors to reproduce specific results and conclusions from the paper'),
    'Jan 2016 - June 2017', 'CSoI Channels Scholar REU',"Center for Science of Information, NSF STC", 
  list('Utilized HPC clusters to efficiently create large data sets pertaining to combinatorial game theory',
       'Analyzed batching strategies of parallel computation to efficiently detect an unknown length of repeating sequences in long strings',
       'Developed a command line interface and file managment system in Python to prevent human error and enhance the usability of codebase'),
) %>% 
  detailed_entries(what=Institution, when=Year, with=Type, why=Desc)
```

# Service
```{r}
tribble(
  ~Date, ~Position, ~Group, ~Institution, ~Desc,
  'Jan 2022 - Present', 'Steering Committee Member', 'Research Software Engineering Association', 'United States',
  c('Committed at least five hours per week to steering committee and other meetings including the Diversity Equity and Inclusion (DEI), Outreach, and Code of Conduct and Moderation working groups', 'Established the DEI Speaker Series and DEI Media Meetings. Currently developing a DEI Toolkit for members'),
   'June 2020 - May 2022', "Co-Chair of Women in High Performance Computing", 'ITaP Research Computing', 'Purdue University', 
  c('Organized and served as the host for invited talks where members shared their work or research', 'Established the \\href{https://www.nicole-brewer.com/long-tales-of-science/}{Long Tales of Science podcast} to continute to improve visibility of women in HPC in spite of discontinuing in-person events in the wake of the COVID-19 pandemic')
) %>% 
  detailed_entries(what=Position, when=Date, with=Group, where=Institution, why=Desc, .protect = FALSE)
```
# Training

```{r}
tribble(
  ~Date, ~Position, ~Title, ~Institution, ~Desc,
  'Aug - Dec 2022', 'K - 12 STEM Education & Outreach', 'Graduate Partners in Science Education', 'Arizona State University', 
  c('created an interactive lesson about parallel and distributed computing and modified existing lessons for remote instruction', 'learned teaching practices that are engaging and inclusive'), 
   "May 2020", 'SDSC Summer Institute', 'San Diego Supercomputer Center', 'Virtual', 
  'Machine learning in R, big data with Spark, parallel programming with Python, and scientific visualization',
  'July 2019', 'Applied Management Principles', 'Krannert Executive Education', 'West Lafayette, IN', 'Purdue\'s "mini-MBA" covering accounting, finance, strategy, marketing, negotiations & problem solving, and entrepreneurial skills essential to effective laboratory and research project managment'
) %>% 
  detailed_entries(what=Position, when=Date, with=Title, where=Institution, why=Desc)
```

# Conference Activity
```{r}
tribble(
  ~Year, ~Title, ~Awarder,
  '2022', '\\textbf{Committee Member}, Reproducibility Challenge', 'SC22',
) %>% 
  brief_entries(what=Title, when=Year, with=Awarder, .protect = FALSE)
```

# Mentorship and Outreach
```{r}
  tribble(
  ~Date, ~Position, ~Group, ~Institution, ~Desc,
  'Oct - Nov 2022', 'Mentor', 'Mentor–Protégé Matching', 'SC22',
  'Participated in virtual activities in the months leading up to the conference and provided career and educational advise to two mentees at the conference',
  'Aug - Nov 2019', 'Staff Advisor', 'Student Cluster Competition', 'SC19', 
  'Mentored students taking a weekly, two credit hour course in preparation for a competition that I had participated in the year prior', 
  'June 2019', 'Mentor', 'Science Gateways Community Institute Hackathon', 'PEARC19' ,
  'Answered students code-related questions over the course of an intensive, three day conference hackathon',
  'Aug 2018 - May 2019', 'Staff Mentor', 'Discover Park Undergraduate Research Internship', 'Purdue University', 
  'Defined the scope of a small project related to our ongoing research projects and met with each student bi-weekly during the course of the semester to help them set achievable short-term goals and guide them through roadblocks they encountered',
  'Aug - Dec 2018', 'Near-Peer Mentor', 'Mentors for Aspiring Girls in Computing', 'Purdue University', 'Led hands-on activities to teach computer science concepts to local middle and high school students in order to improve the recruitment and retention of young women in technology careers'
  ) %>% 
  detailed_entries(what=Position, when=Date, with=Group, where=Institution, why=Desc)
```

# Science Communication and Broader Impacts
```{r}
# if no url, use \\newline
tribble(
 ~ title, ~ type, ~ event, ~ place, ~ date, ~ url,
 'SC22 Mini-series: Reproducibility Initiative (in progress)', 'Host', 'RSE Stories', 'Podcast', 'Nov 2022', 
 'http://us-rse.org/rse-stories/posts/',
 'Trial by Fire', 'Host', 'Long Tales of Science', 'Podcast' , 'May 2022',
 '\\url{https://nicole-brewer.github.io/long-tales-of-science/004/}',
  "Research Software Engineering", "Interviewee", "Hello PhD", "Podcast", "Apr 2022",
 "\\url{http://hellophd.com/2022/03/172-research-software-engineer/}",
 'Call 1-800-HLP-DESK', 'Host', 'Long Tales of Science', 'Podcast', 'Dec 2021', 
 '\\url{https://nicole-brewer.github.io/long-tales-of-science/003/}',
 'Models and Simulations Run on the Cluster and in the Family', 'Host', 'Long Tales of Science', 'Podcast', 'Oct 2020',
 '\\url{https://nicole-brewer.github.io/long-tales-of-science/002/}'
)  %>% 
   brief_entries(glue::glue('\\textbf{<title>} (<type>), <event>, <place>. <url>', .open = "<", .close = ">"), paste0(date, "\\newline"), .protect = FALSE)
```

# Teaching Experience
```{r}
tribble(
  ~Date, ~Position, ~Title, ~Institution, ~Desc,
   "Aug 2015 - May 2016", 'Undergraduate Teaching Assistant', 'Object Oriented Programming', 'Purdue Univeristy', 'Taught object oriented programming in Java, debugging In Intellij, JUnit Testing, and app development in Android Studio in laboratory',
) %>% 
  detailed_entries(what=Position, when=Date, with=Title, where=Institution)
```

# Extracurricular Leadership
```{r}
  tribble(
  ~Date, ~Position, ~Group,
  '2016', '\\textbf{Vice President}, Purdue University Triathlon Club', '',
   '2015', '\\textbf{Social Media Manager}, Purdue University Triathlon Club',  ''
) %>% 
  brief_entries(what=Position, when=Date, with=Group, .protect = FALSE)
# 'Led callouts, executive board meetings, and merchandise orders',
```




<!-- Skills 
Languages Python, R, PHP, JavaScript, Java, C, C#, HTML/CSS
Containers Docker, Kubernetes
Databases Solr, Elasticsearch, MongoDB
Platforms Linux (CentOS, RHEL, Ubuntu), MacOS, Windows
Development Tools Git, Vim, RStudio, IntelliJ, AndroidStudio, Visual Studio, SVN
-->
