#................................................
# In case I have to use docker credentials see:
#    https://stackoverflow.com/a/64051330/8302386
#................................................


on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches: master

name: docker_cv

jobs:
  build:
    name: create the curriculum vitae pdf file
    runs-on: ubuntu-latest
    container:
      image: brewer36/r-vitae:latest
      env:
        ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
    steps:
     - uses: actions/checkout@v2
     - name: render the curriculum vitae
       run: |
         Rscript -e "print(getwd())"
         Rscript -e "rmarkdown::render(input = file.path(getwd(), 'cv.Rmd'), params = list(work_dir = getwd()))"
     - name: Commit files
       run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add the cv.pdf file to the repository"
          git push
     - name: Upload pdf file
       uses: actions/upload-artifact@v1
       with:
         name: pdf
         path: cv.pdf
